// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyNgc1IWPOYx9csBHQ8jBfSKRVmFFtxHY',
    appId: '1:522326705056:android:df018814452c49ae241ac5',
    messagingSenderId: '522326705056',
    projectId: 'wowsalon-2a607',
    storageBucket: 'wowsalon-2a607.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6AmTmaEoWH8l-mJNvqIX0QHhOl-UPF6E',
    appId: '1:522326705056:ios:f726d2b727365940241ac5',
    messagingSenderId: '522326705056',
    projectId: 'wowsalon-2a607',
    storageBucket: 'wowsalon-2a607.firebasestorage.app',
    iosBundleId: 'com.example.wowSalon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6AmTmaEoWH8l-mJNvqIX0QHhOl-UPF6E',
    appId: '1:522326705056:ios:f726d2b727365940241ac5',
    messagingSenderId: '522326705056',
    projectId: 'wowsalon-2a607',
    storageBucket: 'wowsalon-2a607.firebasestorage.app',
    iosBundleId: 'com.example.wowSalon',
  );
}
